### ISSUE TITLE
Handling multi-linears with binary vars involved in the product 

### ISSUE THREAD

**Issue by harshangrjn** [lanl-ansi/POD.jl#55]
Cont: Continuous 
Bin: Binary 

Realized this issue while looking at the gas-network formulation. 

For a bilinear problem of this type, (I think) POD partitions all the cont vars which will "not" be necessary: 
```
max x+y
s.t. 
x - x*y <=k
x_l <= x <= x_u
y \in {0,1}
```

Before including cont vars for partitioning, it is necessary to check if they are in product with cont/bin vars. If cont*bin, since the McC constraints are exact, cont vars need not be partitioned. 

In the case of a ML problem like this, 
```
max x+y+z
s.t. 
x - x*z*y <=k
x_l <= x <= x_u
z_l <= z <= z_u
y \in {0,1}
```

Either of the two methods can be applied: 
1. Let \hat{x} be the lifted var for x*z which takes the usual partitioned, lambda formulation and then \hat{x}*y can take McC without partitioning \hat{x}. 

2. If lambda formulation is applied to the entire term, one can apply the following convexification: 
Let \tilde{x} be the lifted var for x*z*y. Partitions shall be added only on x and z vars. The following constraints will suffice: 

```
Partitioned-lambda formulation constraints on x*z (SOS2/Facet)
\tilde{x} = lambda_1*x_l*z_l + lambda_2*x_l*z_u + lambda_3*x_u*z_l  +lambda_4*x_u*z_u
\sum_i lambda_i = 1
y * \tilde{x}_l <= \tilde{x} <= y * \tilde{x}_u

```
I assume the 2nd method would be computationally efficient.

**Comment by jac0320** [comment]
As I was working on the "linking constraint" in Embedding formulation, I see that necessity in setting up a dedicated OPERATOR to recognize the binary variable products in expression and existing operators. 

This OPERATOR sits in parallel with all other existing operators and converts binary variable products into "non-linear terms". This operator recognize the general form,
```
\prod(X), where x\in\{0,1\} for all x \in X 
```

To resolve these terms, I think we can use the linearization method provided by @harshangrjn, which is
```
z <= x \forall x \in X
z >= \sum{X} - (|X|-1)
```

This works has a basic layout in the latest developing branch "embedding".

**Comment by jac0320** [comment]
A series of implementation is done as #72 is merged. Still, more checking and test cases are required
